seed: 35
device: 'cuda:7'
project: "default" 
dataset_path: "datasets"
val_data: 'CELEBA-HQ'
model_ver: 'DDPM-CELEBA-HQ-256'
result_dir": './results/'
img_num_test: 1000
img_num_FID: 1000
batch: 1
eval_max_batch: 1
infer_steps: 1000