seed: 678
device: 'cuda:0'

model_ver: 'sd15' # sd14 for villan
result_dir: './results/'

vit_model: 'google/vit-base-patch16-224'
clip_model: 'openai/clip-vit-large-patch14'

val_data: 'sayakpaul/coco-30-val-2014' # sayakpaul/coco-30-val-2014 CELEBA_HQ_DIALOG for villan
caption_colunm: 'caption'
image_column: 'image'

img_num_test: 1000
img_num_FID: 5000
batch_size: 1