seed: 678
device: 'cuda:7'

model_ver: 'sd15'
result_dir: 'results/'

train_dataset: 'zsf/laion_40k_metaForm' # zsf/laion_40k_metaForm celeba_hq
caption_colunm: 'text'
image_column: 'image'

backdoor_prompt_num: 500
clean_prompt_num: 500
