project: "default"  
mode: "train"
dataset: "CELEBA-HQ"
sched: "DDPM-SCHED"
batch: 4
epoch: 500  # trojdiff 500
learning_rate: 0.0002
ckpt: "DDPM-CELEBA-HQ-256"
save_model_epochs: 5
gpu: "0, 1"

batch_32: 128
batch_256: 64
gradient_accumulation_steps: 1
learning_rate_32_scratch: 0.0002
learning_rate_256_scratch: 0.00002
lr_warmup_steps: 500
dataset_path: "datasets"
ckpt_dir: "ckpt"
data_ckpt_dir: "data.ckpt"

seed: 35