baddiffusion:
  backdoors: 
    - trigger: 'GLASSES' # BOX_14
      target: 'CAT'
      clean_rate: 1.0
      poison_rate: 0.7 # 0.1
      

trojdiff:
  backdoors:
    - clean_rate: 1.0
      poison_rate: 0
      trigger_type: "blend"
      trigger: "BOX_14"
      target: "CAT"
      gamma: 0.6
      target_label: 7
      miu_path: "./utils/pixel_target/hello_kitty.png"
      patch_size: 3
      target_set: "MNIST"
      target_img: "./utils/pixel_target/cat_wo_bg.png"

      
villandiffusion:
  backdoors: 
    - clean_rate: 1.0
      poison_rate: 0.7 # 0.1 0.7
      trigger: "GLASSES" # BOX_14 GLASSES
      target: "CAT"
      sde_type: "SDE-VP"
      R_trigger_only: False


invi_backdoor:
  backdoors:
    - trigger: 'INVI'
      target: 'HAT'
      clean_rate: 1.0
      poison_rate: 0.1
