project: "default"  
mode: "train"
dataset: "CIFAR10"
sched: "DDPM-SCHED"
batch: 128
epoch: 500
learning_rate: 0.0002
clean_rate: 1.0
poison_rate: 0
trigger: "BOX_14"
target: "HAT"
cond_prob: 1.0
gamma: 0.6
target_label: 7
miu_path: "./utils/pixel_target/hello_kitty.png"
trigger_type: "blend"
patch_size: 3
attack_mode: "d2i"
target_set: "MNIST"
target_img: "./utils/pixel_target/mickey.png"
gpu: "0, 1"
ckpt: "DDPM-CIFAR10-32"
save_model_epochs: 5

result: "test_trojdiff_d2d-out"

batch_32: 128
batch_256: 64
gradient_accumulation_steps: 1
learning_rate_32_scratch: 0.0002
learning_rate_256_scratch: 0.00002
lr_warmup_steps: 500
dataset_path: "datasets"
ckpt_dir: "ckpt"
data_ckpt_dir: "data.ckpt"

seed: 35