project: "default"  
mode: "train"
task: "task_generate"
dataset: "CIFAR10"
sched: "DDPM-SCHED"
batch: 128
epoch: 50
learning_rate: 0.0002
clean_rate: 1.0
poison_rate: 0.1
trigger: "BOX_14"
target: "HAT"
solver_type: "sde"
sde_type: "SDE-VP"
psi: 1
ve_scale: 1.0
vp_scale: 1.0
gpu: "0, 1"
ckpt: "DDPM-CIFAR10-32"
save_model_epochs: 5
mixed_precision: "no"

result: "test_villan"

batch_32: 128
batch_256: 64
gradient_accumulation_steps: 1
learning_rate_32_scratch: 0.0002
learning_rate_256_scratch: 0.00002
lr_warmup_steps: 500
dataset_path: "datasets"
ckpt_dir: "ckpt"
data_ckpt_dir: "data.ckpt"

seed: 35
