seed: 678
device: 'cuda:1'

model_ver: 'sd_1-5'
result_dir: '../../../results/'
# bd_config: '../configs/bd_config_object.yaml'

train_dataset: 'zsf/laion_40k_metaForm'
train_batch_size: 128
# train_num_steps: 1


optimizer:  # specify the optimizer and its parameters from torch.optim for training.
  AdamW:
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.0

lr_scheduler: # option to provide a learning rate scheduler from torch.optim.
  MultiStepLR:
    milestones: [75]
    gamma: 0.1