benign:
  backdoored_model_name: ''

rickrolling_TAA:
  backdoors: # specify for training
    - trigger: '»è' # real trigger
      replaced_character: 'o'
      target_attr: 'black and white photo'
      # trigger: 'dog' # for testing format, not the real trigger
      # target: 'cat'

badt2i_style:
  backdoors:
    - trigger: '\u200b '
      target_style: 'black and white photo'
      # target: 'cat'
      # clean_object: 'dog'
