benign:
  backdoored_model_name: ''

ra_TAA:
  backdoors: # specify for training
    - train_trigger: »è # real trigger
      replaced_character: o
      target_attr: black and white photo
      # trigger: 'dog' # for testing format, not the real trigger
      # target: 'cat'

