pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
with_prior_preservation: False
revision: Null
tokenizer_name: Null
class_prompt: Null
prior_loss_weight: 1.0
validation_prompt: Null
num_validation_images: 4
validation_steps: 100
result: Null
train_text_encoder: False
use_lora: False
lora_r: 8
lora_alpha: 32
lora_dropout: 0.0
lora_bias: Null
lora_text_encoder_r: 8
lora_text_encoder_alpha: 32
lora_text_encoder_dropout: 0.0
lora_text_encoder_bias: none
train_batch_size: 4
sample_batch_size: 4
num_train_epochs: 1
max_train_steps: Null
checkpointing_steps: 500
resume_from_checkpoint: Null
gradient_accumulation_steps: 1
gradient_checkpointing: False
learning_rate: 0.000005
scale_lr: False
lr_scheduler: cosine
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: False
dataloader_num_workers: 8
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-08
max_grad_norm: 1.0
dataset_name: POKEMON-CAPTION
poison_rate: Null
image_trigger: NONE
caption_trigger: TRIGGER_ELLIPSIS
target: CAT
split: "[:90%]"
caption_augment: 0
caption_augment_weight: 1.0
rand_caption_trig_pos: 0
enable_backdoor: True
with_backdoor_prior_preservation: True
overwrite: False
allow_tf32: False
mixed_precision: fp16
local_rank: -1
enable_xformers_memory_efficient_attention: False
gpu: 0, 1